---
- name: Create Rsync dest folder ans install Rsync
  hosts: all
  roles:
    - Createfolder
    - InstallRsync
#  ignore_errors: yes

- name: SourceOS Jobs
  hosts: SourceOS
  roles:
    - Packdata
    - Transferdata
#  ignore_errors: yes

- name: Import creadential, data and run container
  hosts: DestOS
  roles:
    - InstallDocker
    - ImportCredential
    - Runcontainer
  environment:
    PYTHONPATH: "/usr/local/lib/python2.7/dist-packages"
# ignore_errors: yes