---
- name: Pack and transfer data
  shell: "{{ item }}"
  with_items:
  - apt install -y rsync
  - mkdir /migrate
  - docker container exec "{{ container1 }}" /usr/bin/mysqldump -u root --password="{{ DBpassword }}" --all-databases > /migrate/backup.sql
  - tar -cvf /migrate/web.tar /opt/web
  - tar -cvf /migrate/home.tar /home
  - "awk -v LIMIT=1000 -F: '($3>=LIMIT) && ($3!=65534)' /etc/passwd > /migrate/passwd.sync"
  - "awk -v LIMIT=1000 -F: '($3>=LIMIT) && ($3!=65534)' /etc/group > /migrate/group.sync"
  - "awk -v LIMIT=1000 -F: '($3>=LIMIT) && ($3!=35534) {print $1}' /etc/passwd | tee - | egrep -f - /etc/shadow > /migrate/shadow.sync"
  - "awk -v LIMIT=1000 -F: '($3>=LIMIT) && ($3!=65534) {print $1}' /etc/group | tee - | egrep -f - /etc/gshadow > /migrate/gshadow.sync"
  - rsync -avz --no-o --no-g /migrate/ "{{ DestIP }}"::migrate