- name: Ping
  ping:

- name: Show IP, FQDN, hostname
  debug:
    msg: "{{ item }}"
  with_items:
    - "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    - "{{ hostvars[inventory_hostname]['ansible_fqdn'] }}"
    - "{{ hostvars[inventory_hostname]['ansible_hostname'] }}"